### ISSUE TITLE
Error when creating pod from image: log4j.properties file is missing

### ISSUE THREAD

**Issue by Wordenskjold** [GoogleCloudPlatform/elasticsearch-docker#38]
I'm getting the above error when configuring my container to have both a persistent volume for data, and a volume mapping for the config file. See my config file below. It seems to occur when mapping the 'elasticsearchconfig' below. 

The error is fixed by adding an empty log4j.properties file to the configMap.

```
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  containers:
    - image: launcher.gcr.io/google/elasticsearch5
      name: elasticsearch
      volumeMounts:
        - name: elasticsearchdata
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearchconfig
          mountPath: /usr/share/elasticsearch/config
  volumes:
    - name: elasticsearchdata
      persistentVolumeClaim:
        claimName: elasticsearchdata
    - name: elasticsearchconfig
      configMap:
        name: elasticsearchconfig
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearchdata
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
```
